name: Update brains data
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger update
        run: curl --request POST --url 'https://asm-brains-checker.vercel.app/api/brains'
